service: tooling-jest-docker-plus
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    LOCALSTACK_HOST: ${env:LOCALSTACK_HOST, "localhost"}
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:listAllMyBuckets
          Resource: "*"

plugins:
  - serverless-offline

functions:
  api:
    handler: src/index.main
    events:
      - httpApi:
          path: /
          method: get
