service: tooling-jest-docker-plus
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  - serverless-offline

functions:
  api:
    handler: src/index.hello
    events:
      - httpApi:
          path: /
          method: get
