service: app
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
    layers:
      - arn:aws:lambda:us-east-1:472013666864:layer:PrivateModules:1
